# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/xml/full_person_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Full_Person_Info_Form(object):
    def setupUi(self, Full_Person_Info_Form):
        Full_Person_Info_Form.setObjectName("Full_Person_Info_Form")
        Full_Person_Info_Form.resize(926, 349)
        self.perso_name_label = QtWidgets.QLabel(Full_Person_Info_Form)
        self.perso_name_label.setGeometry(QtCore.QRect(30, 20, 371, 41))
        self.perso_name_label.setObjectName("perso_name_label")
        self.update_rb = QtWidgets.QRadioButton(Full_Person_Info_Form)
        self.update_rb.setGeometry(QtCore.QRect(740, 40, 131, 20))
        self.update_rb.setObjectName("update_rb")
        self.update_button = QtWidgets.QPushButton(Full_Person_Info_Form)
        self.update_button.setEnabled(False)
        self.update_button.setGeometry(QtCore.QRect(780, 280, 93, 28))
        self.update_button.setObjectName("update_button")
        self.save_button = QtWidgets.QPushButton(Full_Person_Info_Form)
        self.save_button.setEnabled(False)
        self.save_button.setGeometry(QtCore.QRect(670, 280, 93, 28))
        self.save_button.setObjectName("save_button")
        self.tableWidget = QtWidgets.QTableWidget(Full_Person_Info_Form)
        self.tableWidget.setGeometry(QtCore.QRect(30, 121, 851, 141))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.comboBox = QtWidgets.QComboBox(Full_Person_Info_Form)
        self.comboBox.setGeometry(QtCore.QRect(30, 80, 431, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.show_button = QtWidgets.QPushButton(Full_Person_Info_Form)
        self.show_button.setEnabled(True)
        self.show_button.setGeometry(QtCore.QRect(480, 77, 93, 31))
        self.show_button.setObjectName("show_button")

        self.retranslateUi(Full_Person_Info_Form)
        QtCore.QMetaObject.connectSlotsByName(Full_Person_Info_Form)

    def retranslateUi(self, Full_Person_Info_Form):
        _translate = QtCore.QCoreApplication.translate
        Full_Person_Info_Form.setWindowTitle(_translate("Full_Person_Info_Form", "Form"))
        self.perso_name_label.setText(_translate("Full_Person_Info_Form", "TextLabel"))
        self.update_rb.setText(_translate("Full_Person_Info_Form", "Изменять данные"))
        self.update_button.setText(_translate("Full_Person_Info_Form", "Обновить"))
        self.save_button.setText(_translate("Full_Person_Info_Form", "Сохранить"))
        self.comboBox.setItemText(0, _translate("Full_Person_Info_Form", "Выберете данные"))
        self.comboBox.setItemText(1, _translate("Full_Person_Info_Form", "Другие фамилии\\имена"))
        self.comboBox.setItemText(2, _translate("Full_Person_Info_Form", "Характеристики"))
        self.comboBox.setItemText(3, _translate("Full_Person_Info_Form", "Условия проживания"))
        self.comboBox.setItemText(4, _translate("Full_Person_Info_Form", "Места проживания"))
        self.show_button.setText(_translate("Full_Person_Info_Form", "Показать"))
