# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/xml/search.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Search_Form(object):
    def setupUi(self, Search_Form):
        Search_Form.setObjectName("Search_Form")
        Search_Form.resize(312, 188)
        self.search_parametr_lineedit = QtWidgets.QLineEdit(Search_Form)
        self.search_parametr_lineedit.setGeometry(QtCore.QRect(20, 100, 271, 31))
        self.search_parametr_lineedit.setObjectName("search_parametr_lineedit")
        self.search_paramets_combobox = QtWidgets.QComboBox(Search_Form)
        self.search_paramets_combobox.setGeometry(QtCore.QRect(20, 60, 271, 31))
        self.search_paramets_combobox.setObjectName("search_paramets_combobox")
        self.search_paramets_combobox.addItem("")
        self.search_paramets_combobox.addItem("")
        self.search_paramets_combobox.addItem("")
        self.label = QtWidgets.QLabel(Search_Form)
        self.label.setGeometry(QtCore.QRect(20, 0, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ok_button = QtWidgets.QPushButton(Search_Form)
        self.ok_button.setGeometry(QtCore.QRect(110, 150, 93, 28))
        self.ok_button.setObjectName("ok_button")

        self.retranslateUi(Search_Form)
        QtCore.QMetaObject.connectSlotsByName(Search_Form)

    def retranslateUi(self, Search_Form):
        _translate = QtCore.QCoreApplication.translate
        Search_Form.setWindowTitle(_translate("Search_Form", "Поиск"))
        self.search_paramets_combobox.setItemText(0, _translate("Search_Form", "Фамилия"))
        self.search_paramets_combobox.setItemText(1, _translate("Search_Form", "Имя"))
        self.search_paramets_combobox.setItemText(2, _translate("Search_Form", "Год"))
        self.label.setText(_translate("Search_Form", "Выберете элемент поиска"))
        self.ok_button.setText(_translate("Search_Form", "Ок"))
